# -*- coding: utf-8 -*-
"""Dictionaries

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19YhsDk7CA0f0J2F6PpeMhmMyUCgjK-h8
"""

student = {
    "name":"Aarav",
    "age":14,
    "grade":"9th"
}
print(student)

print(student["name"])

student ["age"] = 15
print(student)

student ["school"] = "DPS"
print(student)

student.pop("grade") == 15
print(student)

for key, value in student.items():
  print(key,":", value)