# -*- coding: utf-8 -*-
"""Questions

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iLXm9aXOxZwdcIRmoZqLC_lcowaGyZ6Y
"""

movie = {
      "title": "Zootopia",
      "year": 2016,
      "genre": "Animation",
      "rating": 8.0
}
print(movie)

print(movie["genre"])

movie["lead_actor"] = "Judy Hopps"
print(movie)

movie["rating"]=9.0
print(movie)

movie.pop("year")
print(movie)

for key, value in movie.items():
  print(key,":",value)